// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function CompressMultiple(arg1) {
  return window['go']['main']['App']['CompressMultiple'](arg1);
}

export function DebugEnabled() {
  return window['go']['main']['App']['DebugEnabled']();
}

export function DebugLog(arg1) {
  return window['go']['main']['App']['DebugLog'](arg1);
}

export function GetAdvice(arg1) {
  return window['go']['main']['App']['GetAdvice'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInputDialog() {
  return window['go']['main']['App']['OpenInputDialog']();
}

export function OpenMultipleDialog() {
  return window['go']['main']['App']['OpenMultipleDialog']();
}

export function OpenOutputDialog(arg1) {
  return window['go']['main']['App']['OpenOutputDialog'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
