// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInputDialog() {
  return window['go']['main']['App']['OpenInputDialog']();
}

export function OpenMultipleDialog() {
  return window['go']['main']['App']['OpenMultipleDialog']();
}

export function OpenOutputDialog(arg1) {
  return window['go']['main']['App']['OpenOutputDialog'](arg1);
}
