// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {compress} from '../models';
import {estimate} from '../models';
import {config} from '../models';
import {encode} from '../models';
import {media} from '../models';
import {presets} from '../models';
import {sysinfo} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function CheckFFmpeg():Promise<main.SystemStatus>;

export function ClearFinished():Promise<Array<compress.TaskStatus>>;

export function Compress(arg1:compress.Job):Promise<string>;

export function CompressMultiple(arg1:Array<compress.Job>):Promise<Array<main.JobAck>>;

export function DebugEnabled():Promise<boolean>;

export function DebugLog(arg1:string):Promise<void>;

export function EstimateSize(arg1:compress.Job):Promise<estimate.Result>;

export function GetAdvice(arg1:compress.Job):Promise<compress.Advice>;

export function GetConfig():Promise<config.Config>;

export function GetEncoders():Promise<encode.Availability>;

export function GetMediaInfo(arg1:string):Promise<media.Info>;

export function GetPresets():Promise<Array<presets.Preset>>;

export function GetTasks():Promise<Array<compress.TaskStatus>>;

export function GetThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetUsage():Promise<sysinfo.Snapshot>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInputDialog():Promise<string>;

export function OpenMultipleDialog():Promise<Array<string>>;

export function OpenOutputDialog(arg1:string):Promise<string>;

export function OpenThumbnailDialog(arg1:string):Promise<string>;

export function RefreshEncoders():Promise<encode.Availability>;

export function SaveConfig(arg1:config.Config):Promise<void>;
